language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
  - cd blog/.vuepress/dist
  - echo 'nanova.me' > CNAME
  - cd -
deploy:
  provider: pages
  target_branch: master
  skip-cleanup: true
  local_dir: blog/.vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: source
