language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
  - cd docs/.vuepress/dist
  - git init
  - git add -A
  - git commit -m 'auto deploy'
  - git push -f git@github.com:kid1412621/kid1412621.github.io.git master
  - cd -
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: source
