name: CI

on: 
  push: 
    branches:
      - source

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: publish
      run: |
        npm run docs:build
        git init
        git add -A
        git commit -m 'auto deploy'
        git push -f git@github.com:kid1412621/kid1412621.github.io.git master
        cd -
